import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import MainContext from '@/src/shared/context/AuthContext';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { routing } from '../../src/i18n/routing';
import { LanguageProvider } from '@/src/shared/context/LanguageContext';
import { ThemeProvider } from '@/src/provider/theme-provider';
import { ToastProvider } from '@/src/shared/context/ToastContext';
import { notFound } from 'next/navigation';
import { cookies } from 'next/headers';
import UIWrapper from '@/src/provider/UIWrapper';
import { NuqsAdapter } from 'nuqs/adapters/next/app';

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const cookieStore = await cookies();
  const theme = cookieStore.get('theme')?.value ?? 'dark';

  console.log(theme, 'sssssssss');

  const isRTL = locale === 'fa';
  return (
    <html lang={locale} dir={isRTL ? 'rtl' : 'ltr'} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <LanguageProvider>
            <ToastProvider>
              <ThemeProvider
                attribute="class"
                defaultTheme={theme}
                enableSystem
                disableTransitionOnChange
              >
                <MainContext>
                  <NuqsAdapter>
                    <UIWrapper>{children}</UIWrapper>
                  </NuqsAdapter>
                </MainContext>
              </ThemeProvider>
            </ToastProvider>
          </LanguageProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
