import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import UIWrapper from '@/src/provider/UIWrapper';
import MainContext from '@/src/shared/context/AuthContext';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { routing } from '../../src/i18n/routing';
import { LanguageProvider } from '@/src/shared/context/LanguageContext';

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, params }: Props) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
  }
  return (
    <html lang="en" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainContext>
          <NextIntlClientProvider>
            <LanguageProvider>
              <UIWrapper>{children}</UIWrapper>
            </LanguageProvider>
          </NextIntlClientProvider>
        </MainContext>
      </body>
    </html>
  );
}
